### ISSUE TITLE
Get to 1.0!

### ISSUE THREAD

**Issue by philschatz** [philschatz/octokat.js#198]
Thanks to great feedback from folks working on the GitHub Desktop app it seems this library has gotten a bit bloated over the years.

It will still take a bit of time to get all of these features in but any feedback or ideas would be appreciated!

# TODO

- [ ] #176 Generate TypeScript (and eventually FlowType) description files
    - The source of these will likely be a set of JSON configuration files which describe the arguments and HTTP Responses
- [ ] #197 Simplify the main codebase so it can focus on delivering data in a type-safe way
    - [ ] Remove the automatic inclusion of plugins like camelCasing, hypermedia, and cache handling. These significantly increase the runtime overhead and cause the typescript definition files to be wrong
    - [ ] Add a `utils` subpackage that contains helpers like `fetchAll(octo)` and `fetchUntil(octo, conditionFn)`
    - [ ] Add a middleware way to add in plugins like the cacheHandler and authorization
- [ ] Change the response to return the data, response object, and maybe parsed headers
- [ ] Add an additional arg for specifying a Preview API header
- [ ] Remove bower support
- [ ] Improve Debugging
  - [ ] Replace PhantomJS with Headless Chrome for tests
  - [ ] Improve test debugging (currently line numbers are wrong and no easy way to add a debugger)
  - [ ] Structure the code so it is easier to read
  - [ ] Support a quick way to add logging
  - [ ] Maybe add dev-mode runtime checks (or just use TypeScript)

# Likely Breaking Changes

- The `Promise` returned by a call to `.fetch()` or others will likely be:
    - _snake_case_ just like the GitHub API
    - a dictionary of the form `{data: ${JSON}, response: ${window.Response}}`
    - not contain functions that were created by parsing the HyperMedia URL templates
